import React from 'react'

import Head from 'next/head'
import Router from 'next/router'

function Home() {
  // React.useEffect(() => {
  //   Router.push('/skills')
  // }, [])

  return (
    <div>
      <Head>
        <title>Victor Maya | Desenvolvedor Front-End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
